// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2Uh9i2od4eIBUsC9WHD16Z4v6ck9sSNU',
    appId: '1:539641269675:web:74cacba013e5e75d2a16ee',
    messagingSenderId: '539641269675',
    projectId: 'letsmeet-228d0',
    authDomain: 'letsmeet-228d0.firebaseapp.com',
    storageBucket: 'letsmeet-228d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeGWw7CqfhOfMu2VbzB0VmndaUIRXexB4',
    appId: '1:539641269675:android:71ac67ddf4cbddff2a16ee',
    messagingSenderId: '539641269675',
    projectId: 'letsmeet-228d0',
    storageBucket: 'letsmeet-228d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoMkNbf68uWuBknw6Zc48XBHAdDfwD9Lg',
    appId: '1:539641269675:ios:ab871ae67f8b25442a16ee',
    messagingSenderId: '539641269675',
    projectId: 'letsmeet-228d0',
    storageBucket: 'letsmeet-228d0.appspot.com',
    iosBundleId: 'chatApplication.com.letsMeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoMkNbf68uWuBknw6Zc48XBHAdDfwD9Lg',
    appId: '1:539641269675:ios:ab871ae67f8b25442a16ee',
    messagingSenderId: '539641269675',
    projectId: 'letsmeet-228d0',
    storageBucket: 'letsmeet-228d0.appspot.com',
    iosBundleId: 'chatApplication.com.letsMeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2Uh9i2od4eIBUsC9WHD16Z4v6ck9sSNU',
    appId: '1:539641269675:web:8e47eaea335798502a16ee',
    messagingSenderId: '539641269675',
    projectId: 'letsmeet-228d0',
    authDomain: 'letsmeet-228d0.firebaseapp.com',
    storageBucket: 'letsmeet-228d0.appspot.com',
  );
}
